[project]
name = "advent-of-code-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lean-bench-sdk",
    "numpy>=2.3.3",
]

[tool.ruff]
exclude = ["solutions/"]

[tool.uv.sources]
lean-bench-sdk = { git = "https://github.com/spikedoanz/lean_bench.git" }
